import type { DashboardTemplate } from "./types";
import { fieldPlaceholder as field, layerPlaceholder as layer } from "./placeholders";

const alertPlaceholders = [
  {
    key: "alert_layer",
    label: "Layer cảnh báo",
    description: "Lớp chứa các phản ánh/cảnh báo/sự kiện cần xử lý.",
    kind: "layer" as const,
    required: true,
    geometryType: "any" as const,
    scope: "template" as const,
  },
  {
    key: "alert_title_field",
    label: "Field tiêu đề",
    kind: "field" as const,
    required: true,
    fieldTypes: ["text", "string", "textarea"],
    sourceKey: "alert_layer",
  },
  {
    key: "alert_severity_field",
    label: "Field mức độ",
    kind: "dimension_field" as const,
    required: true,
    fieldTypes: ["select", "enum", "category", "text", "string"],
    sourceKey: "alert_layer",
  },
  {
    key: "alert_area_field",
    label: "Field khu vực",
    kind: "field" as const,
    required: false,
    fieldTypes: ["select", "enum", "category", "text", "string"],
    sourceKey: "alert_layer",
  },
  {
    key: "alert_date_field",
    label: "Field ngày cảnh báo",
    kind: "date_field" as const,
    required: false,
    fieldTypes: ["date", "datetime", "timestamp", "text"],
    sourceKey: "alert_layer",
  },
  {
    key: "alert_status_field",
    label: "Field trạng thái",
    kind: "dimension_field" as const,
    required: false,
    fieldTypes: ["select", "enum", "category", "text", "string"],
    sourceKey: "alert_layer",
  },
  {
    key: "zone_layer",
    label: "Layer ấp/xã",
    kind: "zone_layer" as const,
    required: true,
    geometryType: "polygon" as const,
    scope: "template" as const,
  },
  {
    key: "zone_label_field",
    label: "Field tên ấp/xã",
    kind: "zone_label_field" as const,
    required: true,
    fieldTypes: ["text", "string", "select", "category"],
    sourceKey: "zone_layer",
  },
];

export const alertTemplate: DashboardTemplate = {
  id: "template-alert",
  code: "alert",
  name: "Cảnh báo",
  description: "Theo dõi danh sách cảnh báo, hoạt động và phân bố mức độ xử lý.",
  category: "alert",
  icon: "bell",
  tags: ["cảnh báo", "phản ánh", "xử lý"],
  widgets: [
    {
      templateWidgetId: "alert-center",
      title: "Trung tâm cảnh báo",
      widgetType: "alert_center",
      layoutConfig: { x: 0, y: 0, w: 4, h: 4 },
      dataSourceConfig: {
        layerId: layer("alert_layer"),
        aggregation: "records",
        titleField: field("alert_title_field"),
        severityField: field("alert_severity_field"),
        areaField: field("alert_area_field"),
        dateField: field("alert_date_field"),
        statusField: field("alert_status_field"),
        limit: 8,
      },
      placeholders: alertPlaceholders,
    },
    {
      templateWidgetId: "alert-feed",
      title: "Hoạt động mới",
      widgetType: "activity_feed",
      layoutConfig: { x: 4, y: 0, w: 4, h: 4 },
      dataSourceConfig: {
        layerId: layer("alert_layer"),
        aggregation: "records",
        titleField: field("alert_title_field"),
        descriptionField: field("alert_status_field"),
        dateField: field("alert_date_field"),
        groupField: field("alert_severity_field"),
        limit: 8,
      },
      placeholders: alertPlaceholders,
    },
    {
      templateWidgetId: "alert-spatial",
      title: "Cảnh báo theo khu vực",
      widgetType: "spatial_alert",
      layoutConfig: { x: 8, y: 0, w: 4, h: 4 },
      dataSourceConfig: {
        aggregation: "records",
        spatial: {
          mode: "alert",
          sourceLayerId: layer("alert_layer"),
          zoneLayerId: layer("zone_layer"),
          zoneLabelField: field("zone_label_field"),
          metricAggregation: "count",
          limit: 8,
        },
      },
      displayConfig: { unit: "vấn đề" },
      placeholders: alertPlaceholders,
    },
    {
      templateWidgetId: "alert-bar-severity",
      title: "Cảnh báo theo mức độ",
      widgetType: "bar",
      layoutConfig: { x: 0, y: 4, w: 6, h: 3 },
      dataSourceConfig: {
        layerId: layer("alert_layer"),
        aggregation: "count",
        dimensionField: field("alert_severity_field"),
        limit: 8,
      },
      displayConfig: { unit: "cảnh báo" },
      placeholders: alertPlaceholders,
    },
    {
      templateWidgetId: "alert-pie-status",
      title: "Cảnh báo theo trạng thái",
      widgetType: "pie",
      layoutConfig: { x: 6, y: 4, w: 6, h: 3 },
      dataSourceConfig: {
        layerId: layer("alert_layer"),
        aggregation: "count",
        dimensionField: field("alert_status_field"),
        limit: 8,
      },
      displayConfig: { unit: "cảnh báo", showLegend: true },
      placeholders: alertPlaceholders,
    },
  ],
};
