import type { DashboardTemplate } from "./types";
import { fieldPlaceholder as field, layerPlaceholder as layer } from "./placeholders";

const sourcePlaceholders = [
  {
    key: "aquaculture_layer",
    label: "Lớp dữ liệu vùng nuôi thủy sản",
    description: "Lớp vùng nuôi hoặc điểm/cơ sở nuôi thủy sản.",
    kind: "layer" as const,
    required: true,
    geometryType: "any" as const,
    scope: "template" as const,
  },
  {
    key: "area_field",
    label: "Trường diện tích",
    kind: "metric_field" as const,
    required: true,
    fieldTypes: ["number", "integer", "decimal", "currency"],
    sourceKey: "aquaculture_layer",
  },
  {
    key: "farming_type_field",
    label: "Trường loại hình nuôi",
    kind: "dimension_field" as const,
    required: true,
    fieldTypes: ["text", "string", "select", "enum", "category"],
    sourceKey: "aquaculture_layer",
  },
  {
    key: "profit_field",
    label: "Trường lợi nhuận hoặc sản lượng",
    kind: "metric_field" as const,
    required: true,
    fieldTypes: ["number", "integer", "decimal", "currency"],
    sourceKey: "aquaculture_layer",
  },
  {
    key: "name_field",
    label: "Trường tên vùng/cơ sở",
    kind: "field" as const,
    required: true,
    fieldTypes: ["text", "string", "select", "category"],
    sourceKey: "aquaculture_layer",
  },
  {
    key: "zone_layer",
    label: "Lớp dữ liệu ấp/xã",
    kind: "zone_layer" as const,
    required: true,
    geometryType: "polygon" as const,
    scope: "template" as const,
  },
  {
    key: "zone_label_field",
    label: "Trường tên ấp/xã",
    kind: "zone_label_field" as const,
    required: true,
    fieldTypes: ["text", "string", "select", "category"],
    sourceKey: "zone_layer",
  },
];

export const aquacultureTemplate: DashboardTemplate = {
  id: "template-aquaculture",
  code: "aquaculture",
  name: "Nuôi thủy sản",
  description: "Bảng điều khiển nhanh cho vùng nuôi, diện tích, cơ cấu và cảnh báo thủy sản.",
  category: "aquaculture",
  icon: "waves",
  tags: ["thủy sản", "vùng nuôi", "diện tích"],
  widgets: [
    {
      templateWidgetId: "aqua-total-area",
      title: "Tổng diện tích nuôi",
      widgetType: "stat",
      layoutConfig: { x: 0, y: 0, w: 3, h: 2 },
      dataSourceConfig: {
        layerId: layer("aquaculture_layer"),
        aggregation: "sum",
        metricField: field("area_field"),
      },
      displayConfig: { theme: "sky", unit: "ha" },
      placeholders: sourcePlaceholders.slice(0, 2),
    },
    {
      templateWidgetId: "aqua-pie-type",
      title: "Cơ cấu loại hình nuôi",
      widgetType: "pie",
      layoutConfig: { x: 3, y: 0, w: 4, h: 3 },
      dataSourceConfig: {
        layerId: layer("aquaculture_layer"),
        aggregation: "sum",
        metricField: field("area_field"),
        dimensionField: field("farming_type_field"),
      },
      displayConfig: { unit: "ha", showLegend: true },
      placeholders: sourcePlaceholders,
    },
    {
      templateWidgetId: "aqua-ranking",
      title: "Top vùng nuôi theo lợi nhuận",
      widgetType: "ranking",
      layoutConfig: { x: 7, y: 0, w: 5, h: 4 },
      dataSourceConfig: {
        layerId: layer("aquaculture_layer"),
        aggregation: "top",
        metricField: field("profit_field"),
        displayFields: [field("name_field"), field("farming_type_field"), field("profit_field")],
        sort: { field: field("profit_field"), direction: "desc" },
        limit: 5,
      },
      displayConfig: {
        variant: "ranking",
        rankingMode: "top",
        nameField: field("name_field"),
        typeField: field("farming_type_field"),
        valueField: field("profit_field"),
        showMedal: true,
        showProgressBar: true,
      },
      placeholders: sourcePlaceholders,
    },
    {
      templateWidgetId: "aqua-alerts",
      title: "Cảnh báo thủy sản",
      widgetType: "alert_center",
      layoutConfig: { x: 0, y: 3, w: 4, h: 4 },
      dataSourceConfig: {
        layerId: layer("alert_layer"),
        aggregation: "records",
        titleField: field("alert_title_field"),
        severityField: field("alert_severity_field"),
        areaField: field("alert_area_field"),
        dateField: field("alert_date_field"),
        statusField: field("alert_status_field"),
        limit: 8,
      },
      placeholders: [
        {
          key: "alert_layer",
          label: "Lớp dữ liệu cảnh báo thủy sản",
          kind: "layer",
          required: true,
          geometryType: "any",
          scope: "template",
        },
        {
          key: "alert_title_field",
          label: "Trường tiêu đề cảnh báo",
          kind: "field",
          required: true,
          fieldTypes: ["text", "string", "textarea"],
          sourceKey: "alert_layer",
        },
        {
          key: "alert_severity_field",
          label: "Trường mức độ",
          kind: "field",
          required: true,
          fieldTypes: ["select", "enum", "category", "text"],
          sourceKey: "alert_layer",
        },
        {
          key: "alert_area_field",
          label: "Trường khu vực",
          kind: "field",
          required: false,
          fieldTypes: ["select", "enum", "category", "text"],
          sourceKey: "alert_layer",
        },
        {
          key: "alert_date_field",
          label: "Trường thời gian",
          kind: "date_field",
          required: false,
          fieldTypes: ["date", "datetime", "timestamp"],
          sourceKey: "alert_layer",
        },
        {
          key: "alert_status_field",
          label: "Trường trạng thái",
          kind: "field",
          required: false,
          fieldTypes: ["select", "enum", "category", "text"],
          sourceKey: "alert_layer",
        },
      ],
    },
    {
      templateWidgetId: "aqua-spatial-ranking",
      title: "Top ấp theo diện tích nuôi",
      widgetType: "spatial_ranking",
      layoutConfig: { x: 4, y: 4, w: 4, h: 4 },
      dataSourceConfig: {
        aggregation: "records",
        spatial: {
          mode: "ranking",
          sourceLayerId: layer("aquaculture_layer"),
          zoneLayerId: layer("zone_layer"),
          zoneLabelField: field("zone_label_field"),
          metricAggregation: "sum",
          metricField: field("area_field"),
          limit: 5,
        },
      },
      displayConfig: { variant: "ranking", unit: "ha" },
      placeholders: sourcePlaceholders,
    },
    {
      templateWidgetId: "aqua-thematic-map",
      title: "Bản đồ diện tích nuôi theo ấp",
      widgetType: "thematic_map",
      layoutConfig: { x: 8, y: 4, w: 4, h: 4 },
      dataSourceConfig: {
        aggregation: "records",
        spatial: {
          mode: "thematic_map",
          sourceLayerId: layer("aquaculture_layer"),
          zoneLayerId: layer("zone_layer"),
          zoneLabelField: field("zone_label_field"),
          metricAggregation: "sum",
          metricField: field("area_field"),
          limit: 20,
        },
      },
      displayConfig: { unit: "ha" },
      placeholders: sourcePlaceholders,
    },
  ],
};
