import type { DashboardTemplate } from "./types";
import { fieldPlaceholder as field, layerPlaceholder as layer } from "./placeholders";

const cropPlaceholders = [
  {
    key: "crop_layer",
    label: "Layer vùng hoa màu",
    description: "Lớp dữ liệu vùng/cơ sở trồng hoa màu.",
    kind: "layer" as const,
    required: true,
    geometryType: "any" as const,
    scope: "template" as const,
  },
  {
    key: "area_field",
    label: "Field diện tích",
    kind: "metric_field" as const,
    required: true,
    fieldTypes: ["number", "integer", "decimal", "currency"],
    sourceKey: "crop_layer",
  },
  {
    key: "crop_type_field",
    label: "Field loại cây trồng",
    kind: "dimension_field" as const,
    required: true,
    fieldTypes: ["text", "string", "select", "enum", "category"],
    sourceKey: "crop_layer",
  },
  {
    key: "profit_field",
    label: "Field lợi nhuận",
    kind: "metric_field" as const,
    required: true,
    fieldTypes: ["number", "integer", "decimal", "currency"],
    sourceKey: "crop_layer",
  },
  {
    key: "name_field",
    label: "Field tên vùng/cơ sở",
    kind: "field" as const,
    required: true,
    fieldTypes: ["text", "string", "select", "category"],
    sourceKey: "crop_layer",
  },
  {
    key: "zone_layer",
    label: "Layer ấp/xã",
    kind: "zone_layer" as const,
    required: true,
    geometryType: "polygon" as const,
    scope: "template" as const,
  },
  {
    key: "zone_label_field",
    label: "Field tên ấp/xã",
    kind: "zone_label_field" as const,
    required: true,
    fieldTypes: ["text", "string", "select", "category"],
    sourceKey: "zone_layer",
  },
];

export const cropTemplate: DashboardTemplate = {
  id: "template-crop",
  code: "crop",
  name: "Hoa màu",
  description: "Tạo nhanh dashboard cơ cấu cây trồng, diện tích và lợi nhuận.",
  category: "crop",
  icon: "sprout",
  tags: ["hoa màu", "cây trồng", "lợi nhuận"],
  widgets: [
    {
      templateWidgetId: "crop-area",
      title: "Tổng diện tích hoa màu",
      widgetType: "stat",
      layoutConfig: { x: 0, y: 0, w: 3, h: 2 },
      dataSourceConfig: {
        layerId: layer("crop_layer"),
        aggregation: "sum",
        metricField: field("area_field"),
      },
      displayConfig: { unit: "ha", theme: "emerald" },
      placeholders: cropPlaceholders.slice(0, 2),
    },
    {
      templateWidgetId: "crop-pie",
      title: "Cơ cấu loại cây trồng",
      widgetType: "pie",
      layoutConfig: { x: 3, y: 0, w: 4, h: 3 },
      dataSourceConfig: {
        layerId: layer("crop_layer"),
        aggregation: "sum",
        metricField: field("area_field"),
        dimensionField: field("crop_type_field"),
      },
      displayConfig: { unit: "ha", showLegend: true },
      placeholders: cropPlaceholders,
    },
    {
      templateWidgetId: "crop-ranking",
      title: "Top lợi nhuận hoa màu",
      widgetType: "ranking",
      layoutConfig: { x: 7, y: 0, w: 5, h: 4 },
      dataSourceConfig: {
        layerId: layer("crop_layer"),
        aggregation: "top",
        metricField: field("profit_field"),
        displayFields: [field("name_field"), field("crop_type_field"), field("profit_field")],
        sort: { field: field("profit_field"), direction: "desc" },
        limit: 5,
      },
      displayConfig: {
        rankingMode: "top",
        nameField: field("name_field"),
        typeField: field("crop_type_field"),
        unit: "triệu đồng/năm",
        showMedal: true,
        showProgressBar: true,
      },
      placeholders: cropPlaceholders,
    },
    {
      templateWidgetId: "crop-treemap",
      title: "Treemap cơ cấu cây trồng",
      widgetType: "treemap",
      layoutConfig: { x: 0, y: 4, w: 4, h: 4 },
      dataSourceConfig: {
        layerId: layer("crop_layer"),
        aggregation: "sum",
        metricField: field("area_field"),
        dimensionField: field("crop_type_field"),
        limit: 10,
      },
      displayConfig: { unit: "ha" },
      placeholders: cropPlaceholders,
    },
    {
      templateWidgetId: "crop-spatial-ranking",
      title: "Top ấp theo diện tích hoa màu",
      widgetType: "spatial_ranking",
      layoutConfig: { x: 4, y: 4, w: 4, h: 4 },
      dataSourceConfig: {
        aggregation: "records",
        spatial: {
          mode: "ranking",
          sourceLayerId: layer("crop_layer"),
          zoneLayerId: layer("zone_layer"),
          zoneLabelField: field("zone_label_field"),
          metricAggregation: "sum",
          metricField: field("area_field"),
          limit: 5,
        },
      },
      displayConfig: { unit: "ha" },
      placeholders: cropPlaceholders,
    },
  ],
};
