import type { DashboardTemplate } from "./types";
import { fieldPlaceholder as field, layerPlaceholder as layer } from "./placeholders";

export const iocTemplate: DashboardTemplate = {
  id: "template-ioc-overview",
  code: "ioc_overview",
  name: "IOC Tổng quan",
  description: "Bộ widget tổng quan cho trung tâm điều hành xã/phường.",
  category: "ioc",
  icon: "dashboard",
  tags: ["IOC", "tổng quan", "bản đồ", "cảnh báo"],
  requirements: [
    { label: "Lớp dữ liệu nguồn", kind: "layer", required: true },
    { label: "Lớp dữ liệu phân vùng", kind: "layer", required: true },
    { label: "Trường tên vùng", kind: "field", required: true },
  ],
  widgets: [
    {
      templateWidgetId: "ioc-total",
      title: "Tổng số đối tượng",
      widgetType: "stat",
      layoutConfig: { x: 0, y: 0, w: 3, h: 2 },
      dataSourceConfig: {
        layerId: layer("source_layer"),
        aggregation: "count",
      },
      displayConfig: { theme: "sky", unit: "đối tượng" },
      placeholders: [
        {
          key: "source_layer",
          label: "Lớp dữ liệu nguồn",
          description: "Lớp dữ liệu chính cần theo dõi.",
          kind: "layer",
          required: true,
          geometryType: "any",
          scope: "template",
        },
      ],
    },
    {
      templateWidgetId: "ioc-minimap",
      title: "Bản đồ tổng quan",
      widgetType: "minimap",
      layoutConfig: { x: 3, y: 0, w: 5, h: 4 },
      displayConfig: {
        showBoundary: true,
        showLegend: true,
        autoFitBounds: true,
      },
    },
    {
      templateWidgetId: "ioc-alerts",
      title: "Trung tâm cảnh báo",
      widgetType: "alert_center",
      layoutConfig: { x: 8, y: 0, w: 4, h: 4 },
      dataSourceConfig: {
        layerId: layer("alert_layer"),
        aggregation: "records",
        titleField: field("alert_title_field"),
        severityField: field("alert_severity_field"),
        areaField: field("alert_area_field"),
        dateField: field("alert_date_field"),
        statusField: field("alert_status_field"),
        limit: 8,
      },
      placeholders: [
        {
          key: "alert_layer",
          label: "Lớp dữ liệu cảnh báo",
          kind: "layer",
          required: true,
          geometryType: "any",
          scope: "template",
        },
        {
          key: "alert_title_field",
          label: "Trường tiêu đề cảnh báo",
          kind: "field",
          required: true,
          fieldTypes: ["text", "string", "textarea"],
          sourceKey: "alert_layer",
        },
        {
          key: "alert_severity_field",
          label: "Trường mức độ",
          kind: "field",
          required: true,
          fieldTypes: ["select", "enum", "category", "text", "string"],
          sourceKey: "alert_layer",
        },
        {
          key: "alert_area_field",
          label: "Trường khu vực",
          kind: "field",
          required: false,
          fieldTypes: ["select", "enum", "category", "text", "string"],
          sourceKey: "alert_layer",
        },
        {
          key: "alert_date_field",
          label: "Trường ngày cảnh báo",
          kind: "date_field",
          required: false,
          fieldTypes: ["date", "datetime", "timestamp"],
          sourceKey: "alert_layer",
        },
        {
          key: "alert_status_field",
          label: "Trường trạng thái",
          kind: "field",
          required: false,
          fieldTypes: ["select", "enum", "category", "text", "string"],
          sourceKey: "alert_layer",
        },
      ],
    },
    {
      templateWidgetId: "ioc-ranking",
      title: "Xếp hạng theo chỉ số",
      widgetType: "ranking",
      layoutConfig: { x: 0, y: 4, w: 4, h: 4 },
      dataSourceConfig: {
        layerId: layer("source_layer"),
        aggregation: "top",
        metricField: field("metric_field"),
        displayFields: [field("name_field"), field("type_field"), field("metric_field")],
        sort: { field: field("metric_field"), direction: "desc" },
        limit: 5,
      },
      displayConfig: {
        variant: "ranking",
        rankingMode: "top",
        nameField: field("name_field"),
        typeField: field("type_field"),
        valueField: field("metric_field"),
        showMedal: true,
        showProgressBar: true,
      },
      placeholders: [
        {
          key: "source_layer",
          label: "Lớp dữ liệu nguồn",
          description: "Lớp dữ liệu chính cần theo dõi.",
          kind: "layer",
          required: true,
          geometryType: "any",
          scope: "template",
        },
        {
          key: "name_field",
          label: "Trường tên đối tượng",
          kind: "field",
          required: true,
          fieldTypes: ["text", "string", "select", "category"],
          sourceKey: "source_layer",
        },
        {
          key: "type_field",
          label: "Trường nhóm phụ",
          kind: "dimension_field",
          required: false,
          fieldTypes: ["text", "string", "select", "category"],
          sourceKey: "source_layer",
        },
        {
          key: "metric_field",
          label: "Trường chỉ số",
          kind: "metric_field",
          required: true,
          fieldTypes: ["number", "integer", "decimal", "currency"],
          sourceKey: "source_layer",
        },
      ],
    },
    {
      templateWidgetId: "ioc-thematic",
      title: "Bản đồ chuyên đề theo khu vực",
      widgetType: "thematic_map",
      layoutConfig: { x: 4, y: 4, w: 4, h: 4 },
      dataSourceConfig: {
        aggregation: "records",
        spatial: {
          mode: "thematic_map",
          sourceLayerId: layer("source_layer"),
          zoneLayerId: layer("zone_layer"),
          zoneLabelField: field("zone_label_field"),
          metricAggregation: "count",
          limit: 20,
        },
      },
      placeholders: [
        {
          key: "source_layer",
          label: "Lớp dữ liệu nguồn",
          description: "Lớp dữ liệu chính cần theo dõi.",
          kind: "layer",
          required: true,
          geometryType: "any",
          scope: "template",
        },
        {
          key: "zone_layer",
          label: "Lớp dữ liệu phân vùng",
          kind: "zone_layer",
          required: true,
          geometryType: "polygon",
          scope: "template",
        },
        {
          key: "zone_label_field",
          label: "Trường tên vùng",
          kind: "zone_label_field",
          required: true,
          fieldTypes: ["text", "string", "select", "category"],
          sourceKey: "zone_layer",
        },
      ],
    },
    {
      templateWidgetId: "ioc-spatial-alert",
      title: "Cảnh báo theo khu vực",
      widgetType: "spatial_alert",
      layoutConfig: { x: 8, y: 4, w: 4, h: 4 },
      dataSourceConfig: {
        aggregation: "records",
        spatial: {
          mode: "alert",
          sourceLayerId: layer("alert_layer"),
          zoneLayerId: layer("zone_layer"),
          zoneLabelField: field("zone_label_field"),
          metricAggregation: "count",
          limit: 8,
        },
      },
      placeholders: [
        {
          key: "alert_layer",
          label: "Lớp dữ liệu cảnh báo",
          kind: "layer",
          required: true,
          geometryType: "any",
          scope: "template",
        },
        {
          key: "zone_layer",
          label: "Lớp dữ liệu phân vùng",
          kind: "zone_layer",
          required: true,
          geometryType: "polygon",
          scope: "template",
        },
        {
          key: "zone_label_field",
          label: "Trường tên vùng",
          kind: "zone_label_field",
          required: true,
          fieldTypes: ["text", "string", "varchar", "char", "select", "category"],
          sourceKey: "zone_layer",
        },
      ],
    },
  ],
};
