import type { DashboardTemplate } from "./types";
import { fieldPlaceholder as field, layerPlaceholder as layer } from "./placeholders";

const irrigationPlaceholders = [
  {
    key: "irrigation_layer",
    label: "Lớp dữ liệu thủy lợi",
    description: "Lớp tuyến/kênh/công trình thủy lợi cần theo dõi.",
    kind: "layer" as const,
    required: true,
    geometryType: "any" as const,
    scope: "template" as const,
  },
  {
    key: "length_field",
    label: "Trường chiều dài",
    kind: "metric_field" as const,
    required: true,
    fieldTypes: ["number", "integer", "decimal", "currency"],
    sourceKey: "irrigation_layer",
  },
  {
    key: "name_field",
    label: "Trường tên công trình/tuyến",
    kind: "field" as const,
    required: true,
    fieldTypes: ["text", "string", "select", "category"],
    sourceKey: "irrigation_layer",
  },
  {
    key: "condition_field",
    label: "Trường tình trạng",
    kind: "dimension_field" as const,
    required: true,
    fieldTypes: ["text", "string", "select", "enum", "category"],
    sourceKey: "irrigation_layer",
  },
  {
    key: "type_field",
    label: "Trường loại công trình",
    kind: "dimension_field" as const,
    required: false,
    fieldTypes: ["text", "string", "select", "enum", "category"],
    sourceKey: "irrigation_layer",
  },
  {
    key: "zone_layer",
    label: "Lớp dữ liệu ấp/xã",
    kind: "zone_layer" as const,
    required: true,
    geometryType: "polygon" as const,
    scope: "template" as const,
  },
  {
    key: "zone_label_field",
    label: "Trường tên ấp/xã",
    kind: "zone_label_field" as const,
    required: true,
    fieldTypes: ["text", "string", "select", "category"],
    sourceKey: "zone_layer",
  },
];

export const irrigationTemplate: DashboardTemplate = {
  id: "template-irrigation",
  code: "irrigation",
  name: "Thủy lợi",
  description: "Theo dõi tuyến, công trình thủy lợi và tình trạng xuống cấp theo khu vực.",
  category: "irrigation",
  icon: "droplets",
  tags: ["thủy lợi", "công trình", "kênh mương"],
  widgets: [
    {
      templateWidgetId: "irrigation-length",
      title: "Tổng chiều dài tuyến",
      widgetType: "stat",
      layoutConfig: { x: 0, y: 0, w: 3, h: 2 },
      dataSourceConfig: {
        layerId: layer("irrigation_layer"),
        aggregation: "sum",
        metricField: field("length_field"),
      },
      displayConfig: { unit: "km", theme: "sky" },
      placeholders: irrigationPlaceholders,
    },
    {
      templateWidgetId: "irrigation-count",
      title: "Số công trình thủy lợi",
      widgetType: "stat",
      layoutConfig: { x: 3, y: 0, w: 3, h: 2 },
      dataSourceConfig: {
        layerId: layer("irrigation_layer"),
        aggregation: "count",
      },
      displayConfig: { unit: "công trình", theme: "emerald" },
      placeholders: irrigationPlaceholders.slice(0, 1),
    },
    {
      templateWidgetId: "irrigation-alerts",
      title: "Công trình cần xử lý",
      widgetType: "alert_center",
      layoutConfig: { x: 6, y: 0, w: 3, h: 4 },
      dataSourceConfig: {
        layerId: layer("irrigation_layer"),
        aggregation: "records",
        titleField: field("name_field"),
        severityField: field("condition_field"),
        areaField: field("type_field"),
        statusField: field("condition_field"),
        limit: 8,
      },
      placeholders: irrigationPlaceholders,
    },
    {
      templateWidgetId: "irrigation-minimap",
      title: "Bản đồ thủy lợi",
      widgetType: "minimap",
      layoutConfig: { x: 9, y: 0, w: 3, h: 4 },
      displayConfig: { showBoundary: true, autoFitBounds: true },
    },
    {
      templateWidgetId: "irrigation-summary",
      title: "Công trình theo ấp",
      widgetType: "spatial_summary",
      layoutConfig: { x: 0, y: 4, w: 4, h: 4 },
      dataSourceConfig: {
        aggregation: "records",
        spatial: {
          mode: "summary",
          sourceLayerId: layer("irrigation_layer"),
          zoneLayerId: layer("zone_layer"),
          zoneLabelField: field("zone_label_field"),
          metricAggregation: "count",
          limit: 20,
        },
      },
      displayConfig: { unit: "công trình" },
      placeholders: irrigationPlaceholders,
    },
    {
      templateWidgetId: "irrigation-ranking",
      title: "Khu vực nhiều công trình",
      widgetType: "spatial_ranking",
      layoutConfig: { x: 4, y: 4, w: 4, h: 4 },
      dataSourceConfig: {
        aggregation: "records",
        spatial: {
          mode: "ranking",
          sourceLayerId: layer("irrigation_layer"),
          zoneLayerId: layer("zone_layer"),
          zoneLabelField: field("zone_label_field"),
          metricAggregation: "count",
          limit: 5,
        },
      },
      displayConfig: { unit: "công trình" },
      placeholders: irrigationPlaceholders,
    },
  ],
};
