import type { DashboardTemplate } from "./types";
import { fieldPlaceholder as field, layerPlaceholder as layer } from "./placeholders";

const ricePlaceholders = [
  {
    key: "rice_layer",
    label: "Layer vùng lúa",
    description: "Lớp vùng/điểm dữ liệu canh tác lúa.",
    kind: "layer" as const,
    required: true,
    geometryType: "any" as const,
    scope: "template" as const,
  },
  {
    key: "area_field",
    label: "Field diện tích",
    kind: "metric_field" as const,
    required: true,
    fieldTypes: ["number", "integer", "decimal", "currency"],
    sourceKey: "rice_layer",
  },
  {
    key: "production_field",
    label: "Field sản lượng",
    kind: "metric_field" as const,
    required: true,
    fieldTypes: ["number", "integer", "decimal", "currency"],
    sourceKey: "rice_layer",
  },
  {
    key: "cultivation_type_field",
    label: "Field loại hình canh tác",
    kind: "dimension_field" as const,
    required: true,
    fieldTypes: ["text", "string", "select", "enum", "category"],
    sourceKey: "rice_layer",
  },
  {
    key: "profit_per_ha_field",
    label: "Field lợi nhuận/ha",
    kind: "metric_field" as const,
    required: true,
    fieldTypes: ["number", "integer", "decimal", "currency"],
    sourceKey: "rice_layer",
  },
  {
    key: "name_field",
    label: "Tên vùng lúa",
    kind: "field" as const,
    required: true,
    fieldTypes: ["text", "string", "varchar", "char", "select", "enum", "dictionary", "category"],
    sourceKey: "rice_layer",
  },
  {
    key: "season_date_field",
    label: "Field ngày/mùa vụ",
    kind: "date_field" as const,
    required: true,
    fieldTypes: ["date", "datetime", "timestamp", "text"],
    sourceKey: "rice_layer",
  },
  {
    key: "zone_layer",
    label: "Layer ấp/xã",
    kind: "zone_layer" as const,
    required: true,
    geometryType: "polygon" as const,
    scope: "template" as const,
  },
  {
    key: "zone_label_field",
    label: "Field tên ấp/xã",
    kind: "zone_label_field" as const,
    required: true,
    fieldTypes: ["text", "string", "select", "category"],
    sourceKey: "zone_layer",
  },
];

export const riceTemplate: DashboardTemplate = {
  id: "template-rice",
  code: "rice",
  name: "Lúa",
  description: "Theo dõi diện tích, sản lượng, lợi nhuận/ha và mùa vụ lúa.",
  category: "rice",
  icon: "wheat",
  tags: ["lúa", "diện tích", "sản lượng"],
  widgets: [
    {
      templateWidgetId: "rice-area",
      title: "Tổng diện tích lúa",
      widgetType: "stat",
      layoutConfig: { x: 0, y: 0, w: 3, h: 2 },
      dataSourceConfig: {
        layerId: layer("rice_layer"),
        aggregation: "sum",
        metricField: field("area_field"),
      },
      displayConfig: { unit: "ha", theme: "emerald" },
      placeholders: ricePlaceholders.slice(0, 2),
    },
    {
      templateWidgetId: "rice-production",
      title: "Tổng sản lượng",
      widgetType: "stat",
      layoutConfig: { x: 3, y: 0, w: 3, h: 2 },
      dataSourceConfig: {
        layerId: layer("rice_layer"),
        aggregation: "sum",
        metricField: field("production_field"),
      },
      displayConfig: { unit: "tấn", theme: "amber" },
      placeholders: ricePlaceholders.slice(0, 3),
    },
    {
      templateWidgetId: "rice-bar-type",
      title: "Diện tích theo loại hình canh tác",
      widgetType: "bar",
      layoutConfig: { x: 6, y: 0, w: 6, h: 3 },
      dataSourceConfig: {
        layerId: layer("rice_layer"),
        aggregation: "sum",
        metricField: field("area_field"),
        dimensionField: field("cultivation_type_field"),
        sort: { field: field("area_field"), direction: "desc" },
        limit: 8,
      },
      displayConfig: { unit: "ha" },
      placeholders: ricePlaceholders,
    },
    {
      templateWidgetId: "rice-ranking-profit",
      title: "Top lợi nhuận/ha",
      widgetType: "ranking",
      layoutConfig: { x: 0, y: 3, w: 4, h: 4 },
      dataSourceConfig: {
        layerId: layer("rice_layer"),
        aggregation: "top",
        metricField: field("profit_per_ha_field"),
        displayFields: [field("name_field"), field("cultivation_type_field"), field("profit_per_ha_field")],
        sort: { field: field("profit_per_ha_field"), direction: "desc" },
        limit: 5,
      },
      displayConfig: {
        rankingMode: "top",
        nameField: field("name_field"),
        typeField: field("cultivation_type_field"),
        unit: "triệu đồng/ha",
        showMedal: true,
        showProgressBar: true,
      },
      placeholders: ricePlaceholders,
    },
    {
      templateWidgetId: "rice-seasonal",
      title: "Lịch mùa vụ",
      widgetType: "seasonal_calendar",
      layoutConfig: { x: 4, y: 3, w: 4, h: 4 },
      dataSourceConfig: {
        layerId: layer("rice_layer"),
        aggregation: "records",
        titleField: field("name_field"),
        dateField: field("season_date_field"),
        groupField: field("cultivation_type_field"),
        limit: 12,
      },
      placeholders: ricePlaceholders,
    },
    {
      templateWidgetId: "rice-thematic",
      title: "Bản đồ diện tích lúa theo ấp",
      widgetType: "thematic_map",
      layoutConfig: { x: 8, y: 3, w: 4, h: 4 },
      dataSourceConfig: {
        aggregation: "records",
        spatial: {
          mode: "thematic_map",
          sourceLayerId: layer("rice_layer"),
          zoneLayerId: layer("zone_layer"),
          zoneLabelField: field("zone_label_field"),
          metricAggregation: "sum",
          metricField: field("area_field"),
          limit: 20,
        },
      },
      displayConfig: { unit: "ha" },
      placeholders: ricePlaceholders,
    },
  ],
};
